name: Daily Python Script at 21:10 IST

on:
  schedule:
    - cron: '40 15 * * *'  # 21:10 IST
  workflow_dispatch:        # Manual run option

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python main.py

      - name: Upload CSV output
        uses: actions/upload-artifact@v4
        with:
          name: output-csv
          path: output.csv
